port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: AKUN1
    server: 104.17.3.81
    type: vmess
    port: 443
    uuid: 3b01a777-55e7-49f6-8637-d94ee69607c6
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vms.lifetime05.workers.dev
    network: ws
    ws-opts:
      path: /172.105.62.71-2443
      headers:
        Host: vms.lifetime05.workers.dev
    udp: true
  - name: AKUN2
    server: 104.17.3.81
    port: 443
    type: vless
    uuid: fc60147e-76b8-4bc5-b691-90b2da79e3d2
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bonjert.bonjert86.workers.dev
    network: ws
    ws-opts:
      path: /43.218.77.16-1443
      headers:
        Host: bonjert.bonjert86.workers.dev
    udp: true
  - name: AKUN3
    server: 104.17.3.81
    port: 443
    type: vless
    uuid: fc60147e-76b8-4bc5-b691-90b2da79e3d2
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bonjert.bonjert86.workers.dev
    network: ws
    ws-opts:
      path: /43.218.77.16-1443
      headers:
        Host: bonjert.bonjert86.workers.dev
    udp: true

proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: AKUN1
    server: 104.17.3.81
    port: 443
    type: trojan
    password: 86768774-70b2-4c15-80c3-02066fb1e3b6
    skip-cert-verify: true
    sni: bonjert.bonjert86.workers.dev
    network: ws
    ws-opts:
      path: /8.222.220.81-25435
      headers:
        Host: bonjert.bonjert86.workers.dev
    udp: true
  - name: AKUN2
    server: 104.17.3.81
    port: 443
    type: vless
    uuid: fc60147e-76b8-4bc5-b691-90b2da79e3d2
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bonjert.bonjert86.workers.dev
    network: ws
    ws-opts:
      path: /43.218.77.16-1443
      headers:
        Host: bonjert.bonjert86.workers.dev
    udp: true
  - name: AKUN3
    server: 104.17.3.81
    port: 443
    type: vless
    uuid: fc60147e-76b8-4bc5-b691-90b2da79e3d2
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: bonjert.bonjert86.workers.dev
    network: ws
    ws-opts:
      path: /43.218.77.16-1443
      headers:
        Host: bonjert.bonjert86.workers.dev
    udp: true

proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  




